name: Deploy to AWS lambda

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  update_aws_lambda:
    name: Deploy to AWS Lambda
    runs-on: ubuntu-latest
    
    steps:
  
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16.16.0
          
      - name: Build docusign webhook lambda
        run: |
          cd docusign-webhook
          npm i
          npx tsc
        
      - name: Zip webhook output
        uses: vimtor/action-zip@v1
        with:
          files: .
          dest: docusign-webhook.zip
          
      - name: Deploy webhook lambda to AWS
        uses: appleboy/lambda-action@v0.1.5
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: thinktech-webhook
          zip_file: docusign-wehbook.zip
      
      - name: Build form sign request lambda
        run: |
          cd ..
          cd form-sign-request
          npm i
          npx tsc

      - name: Zip form sign request output
        uses: vimtor/action-zip@v1
        with:
          files: .
          dest: sign-request.zip

      # TODO
      # - name: Deploy sign request lambda to AWS
      #   uses: appleboy/lambda-action@v0.1.5
      #   with:
      #     aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws_region: ${{ secrets.AWS_REGION }}
      #     function_name: thinktech-webhook
      #     zip_file: sign-request.zip